language: scala
services:
  - docker
branches:
  except:
    - gh-pages
script:
- docker-compose run sbt-redis bash -c "./build/test.sh"
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
sudo: false
