sbt-redis:
  build: .
  dockerfile: ./build/Dockerfile
  ports:
    - "15005:5005"
    - "16379:6379"
  command: sbt
  volumes:
    - ./:/app
    - ~/.ivy2:/root/.ivy2
    - ~/.m2:/root/.m2
    - ~/.ssh/:/root/.ssh/
  environment:
    - TRAVIS_PULL_REQUEST
    - TRAVIS_BRANCH
    - ENCRYPTION_PASSWORD
    - SBT_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dfile.encoding=UTF-8 -Xms512m -Xmx1536m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC
